---
title: "Lab One"
author: "Jonathan Rochelle, Alejandra Garcia Isaza, Shaina Trevino"
date: "1/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries}
library(tidyverse)
library(rio)
library(here)
```

```{r import_data}
data <- import(here("Data", "rstats_tweets.rds"),
               setclass = "tbl_df")
```

```{r, commit 2}
pd<- data %>%
  count(screen_name) %>%
  arrange(desc(n)) %>%
  dplyr::slice(1:25) %>%
  mutate(screen_name = factor(screen_name), 
         screen_name = forcats::fct_reorder(screen_name, n))

ggplot(pd, aes(x = screen_name, y = n)) +
  geom_col() +
  coord_flip()
```

```{r, commit 3, fig.width = 10, fig.height = 10}
pd<- data %>%
  count(screen_name) %>%
  arrange(desc(n)) %>%
  dplyr::slice(1:25) %>%
  mutate(screen_name = factor(screen_name), 
         screen_name = forcats::fct_reorder(screen_name, n))

ggplot(pd, aes(x = screen_name, y = n), size = "20") +
  geom_col(fill = "cornflowerblue", alpha = .75) +
  coord_flip() +
  theme_minimal(base_size = 20) +
  labs(title = "Most prolific #rstats tweeters",
       subtitle = "Top 25 screen names displayed",
       y = "Count",
       x = "Twitter Screen Name",
       caption = "Data from Mike Kearny, distributed via #tidytuesday")
```

```{r ST_plotdata}
pd1 <- data %>% 
  mutate(month = lubridate::round_date(created_at, "months")) %>% 
  filter(month < lubridate::as_datetime("2019-01-01 00:00:00")) 

pd2 <- pd1 %>% 
  count(month)
```

```{r commit4}
ggplot(pd2, aes(x = month, y = n)) +
  geom_smooth() +
  geom_line()
```

```{r, commit 5, fig.width = 10, fig.height= 10 }
ggplot(pd2, aes(x = month, y = n)) +
  geom_smooth(se = FALSE, color = "magenta", size = 2) +
  geom_line(color = "gray40", size = 2) +
  geom_area(fill = "cornflowerblue", alpha = 0.3) +
  theme_minimal(base_size = 20) +
  labs(title = "Growth of the #rstats hashtag on twitter over time",
       y = "Number of #rstats tweets",
       x = "Year (data summarized by month)",
       caption = "Data from Mike Kearny, distributed via #tidytuesday")